In [15]:


import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [85]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
sample=pd.read_csv('sample.csv')

In [86]:
#training data 
train.head()

         date  hour  demand
0  2018-08-18     9      91
1  2018-08-18    10      21
2  2018-08-18    13      23
3  2018-08-18    14     104
4  2018-08-18    15      81

In [87]:
#testing data 
test.head()

         date  hour
0  2021-03-01     0
1  2021-03-01     1
2  2021-03-01     2
3  2021-03-01     3
4  2021-03-01     5

In [63]:
#sample data 
sample.head()

         date  hour  demand
0  2021-03-01     0       0
1  2021-03-01     1       0
2  2021-03-01     2       0
3  2021-03-01     3       0
4  2021-03-01     5       0

In [88]:
dataset = train
dataset["Month"] = pd.to_datetime(train["date"]).dt.month
dataset["Year"] = pd.to_datetime(train["date"]).dt.year
dataset["Date"] = pd.to_datetime(train["date"]).dt.date
dataset["Time"] = pd.to_datetime(train["date"]).dt.time
dataset["Week"] = pd.to_datetime(train["date"]).dt.week
dataset["Day"] = pd.to_datetime(train["date"]).dt.day_name()
dataset = train.set_index("date")
dataset.index = pd.to_datetime(dataset.index)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

In [89]:
dataset.head()

            hour  demand  Month  Year        Date      Time  Week       Day
date
2018-08-18     9      91      8  2018  2018-08-18  00:00:00    33  Saturday
2018-08-18    10      21      8  2018  2018-08-18  00:00:00    33  Saturday
2018-08-18    13      23      8  2018  2018-08-18  00:00:00    33  Saturday
2018-08-18    14     104      8  2018  2018-08-18  00:00:00    33  Saturday
2018-08-18    15      81      8  2018  2018-08-18  00:00:00    33  Saturday

In [94]:
tdataset = test
tdataset["Month"] = pd.to_datetime(test["date"]).dt.month
tdataset["Year"] = pd.to_datetime(test["date"]).dt.year
tdataset["Date"] = pd.to_datetime(test["date"]).dt.date
tdataset["Time"] = pd.to_datetime(test["date"]).dt.time
tdataset["Week"] = pd.to_datetime(test["date"]).dt.week
tdataset["Day"] = pd.to_datetime(test["date"]).dt.day_name()
tdataset = test.set_index("date")
tdataset.index = pd.to_datetime(tdataset.index)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

In [95]:
tdataset.head()

            hour  Month  Year        Date      Time  Week     Day
date
2021-03-01     0      3  2021  2021-03-01  00:00:00     9  Monday
2021-03-01     1      3  2021  2021-03-01  00:00:00     9  Monday
2021-03-01     2      3  2021  2021-03-01  00:00:00     9  Monday
2021-03-01     3      3  2021  2021-03-01  00:00:00     9  Monday
2021-03-01     5      3  2021  2021-03-01  00:00:00     9  Monday

In [103]:
NewDataSet = dataset.resample('D').mean()

In [104]:
TestData = NewDataSet.tail(100)

Training_Set = NewDataSet.iloc[:,0:1]

Training_Set = Training_Set[:-60]

In [105]:
Training_Set = Training_Set.values
sc = MinMaxScaler(feature_range=(0, 1))
Train = sc.fit_transform(Training_Set)

In [106]:
X_Train = []
Y_Train = []
for i in range(60, Train.shape[0]):
    
    # X_Train 0-59 
    X_Train.append(Train[i-60:i])
    
    # Y Would be 60 th Value based on past 60 Values 
    Y_Train.append(Train[i])

# Convert into Numpy Array
X_Train = np.array(X_Train)
Y_Train = np.array(Y_Train)

print(X_Train.shape)
print(Y_Train.shape)

(806, 60, 1)
(806, 1)

In [107]:
X_Train = np.reshape(X_Train, newshape=(X_Train.shape[0], X_Train.shape[1], 1))
X_Train.shape

(806, 60, 1)

In [109]:
regressor = Sequential()
regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_Train.shape[1], 1)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))


regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

regressor.add(Dense(units = 1))

regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')